server:
 # port: 8890
  servlet:
    context-path: /
 # address: 0.0.0.0
 # address: 0.0.0.0
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  profiles:
    include: dev
ue:
  config-file: static/ueditor/jsp/config.json #resources目录下配置文件的位置
  server-url: /ueditor.do #服务器统一请求接口路径
